[2024-10-09T00:47:44.688+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:47:44.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:47:44.698+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:47:44.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:47:44.725+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:47:44.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:47:44.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:47:44.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.218 seconds
[2024-10-09T00:48:15.529+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:48:15.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:48:15.536+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:48:15.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:48:15.543+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:48:15.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:48:15.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:48:15.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.096 seconds
[2024-10-09T00:48:45.645+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:48:45.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:48:45.649+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:48:45.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:48:45.654+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:48:45.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:48:45.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:48:45.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.043 seconds
[2024-10-09T00:49:16.119+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:49:16.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:49:16.123+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:49:16.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:49:16.128+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:49:16.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:49:16.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:49:16.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.041 seconds
[2024-10-09T00:49:46.492+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:49:46.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:49:46.497+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:49:46.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:49:46.502+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:49:46.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:49:46.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:49:46.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.060 seconds
[2024-10-09T00:50:16.766+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:50:16.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:50:16.771+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:50:16.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:50:16.775+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:50:16.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:50:16.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:50:16.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.043 seconds
[2024-10-09T00:50:47.297+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:50:47.299+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:50:47.302+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:50:47.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:50:47.307+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:50:47.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:50:47.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:50:47.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.046 seconds
[2024-10-09T00:51:18.102+0000] {processor.py:186} INFO - Started process (PID=513) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:51:18.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:51:18.107+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:51:18.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:51:18.112+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:51:18.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:51:18.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:51:18.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.046 seconds
[2024-10-09T00:51:48.993+0000] {processor.py:186} INFO - Started process (PID=578) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:51:48.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:51:49.001+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:51:49.000+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:51:49.005+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:51:49.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:51:49.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:51:49.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.049 seconds
[2024-10-09T00:52:19.603+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:52:19.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:52:19.608+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:52:19.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:52:19.612+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:52:19.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:52:19.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:52:19.640+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.047 seconds
[2024-10-09T00:52:50.037+0000] {processor.py:186} INFO - Started process (PID=708) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:52:50.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:52:50.043+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:52:50.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:52:50.047+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:52:50.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:52:50.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:52:50.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.109 seconds
[2024-10-09T00:53:20.840+0000] {processor.py:186} INFO - Started process (PID=773) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:53:20.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:53:20.887+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:53:20.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:53:20.902+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:53:20.896+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:53:20.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:53:20.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.195 seconds
[2024-10-09T00:53:51.897+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:53:51.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:53:51.902+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:53:51.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:53:51.907+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:53:51.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:53:51.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:53:51.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.044 seconds
[2024-10-09T00:54:22.064+0000] {processor.py:186} INFO - Started process (PID=903) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:54:22.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:54:22.069+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:54:22.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:54:22.092+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:54:22.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:54:22.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:54:22.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.092 seconds
[2024-10-09T00:54:52.302+0000] {processor.py:186} INFO - Started process (PID=967) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:54:52.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:54:52.309+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:54:52.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:54:52.314+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:54:52.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:54:52.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:54:52.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.071 seconds
[2024-10-09T00:55:22.623+0000] {processor.py:186} INFO - Started process (PID=1032) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:55:22.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:55:22.628+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:55:22.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:55:22.633+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:55:22.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:55:22.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:55:22.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T00:55:52.923+0000] {processor.py:186} INFO - Started process (PID=1098) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:55:52.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:55:52.928+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:55:52.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:55:52.933+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:55:52.931+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:55:52.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:55:52.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.051 seconds
[2024-10-09T00:56:23.109+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:56:23.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:56:23.113+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:56:23.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:56:23.118+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:56:23.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:56:23.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:56:23.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T00:56:53.456+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:56:53.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:56:53.461+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:56:53.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:56:53.467+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:56:53.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:56:53.468+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:56:53.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.051 seconds
[2024-10-09T00:57:23.918+0000] {processor.py:186} INFO - Started process (PID=1292) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:57:23.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:57:23.923+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:57:23.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:57:23.928+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:57:23.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:57:23.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:57:23.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.046 seconds
[2024-10-09T00:57:54.268+0000] {processor.py:186} INFO - Started process (PID=1357) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:57:54.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:57:54.272+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:57:54.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:57:54.277+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:57:54.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:57:54.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:57:54.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.047 seconds
[2024-10-09T00:58:24.926+0000] {processor.py:186} INFO - Started process (PID=1422) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:58:24.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:58:24.930+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:58:24.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:58:24.935+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:58:24.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:58:24.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:58:24.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.049 seconds
[2024-10-09T00:58:55.147+0000] {processor.py:186} INFO - Started process (PID=1486) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:58:55.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:58:55.152+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:58:55.152+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:58:55.157+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:58:55.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:58:55.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:58:55.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T00:59:25.266+0000] {processor.py:186} INFO - Started process (PID=1550) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:59:25.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:59:25.271+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:59:25.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:59:25.275+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:59:25.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:59:25.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:59:25.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.045 seconds
[2024-10-09T00:59:55.836+0000] {processor.py:186} INFO - Started process (PID=1616) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:59:55.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T00:59:55.843+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:59:55.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:59:55.848+0000] {logging_mixin.py:190} INFO - [2024-10-09T00:59:55.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T00:59:55.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T00:59:55.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.065 seconds
[2024-10-09T01:00:26.023+0000] {processor.py:186} INFO - Started process (PID=1681) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:00:26.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:00:26.029+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:00:26.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:00:26.034+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:00:26.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:00:26.035+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:00:26.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.056 seconds
[2024-10-09T01:00:56.166+0000] {processor.py:186} INFO - Started process (PID=1746) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:00:56.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:00:56.172+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:00:56.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:00:56.176+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:00:56.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:00:56.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:00:56.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.047 seconds
[2024-10-09T01:01:26.779+0000] {processor.py:186} INFO - Started process (PID=1811) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:01:26.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:01:26.784+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:01:26.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:01:26.789+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:01:26.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:01:26.790+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:01:26.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.054 seconds
[2024-10-09T01:01:57.070+0000] {processor.py:186} INFO - Started process (PID=1876) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:01:57.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:01:57.075+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:01:57.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:01:57.080+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:01:57.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:01:57.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:01:57.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T01:02:27.608+0000] {processor.py:186} INFO - Started process (PID=1941) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:02:27.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:02:27.612+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:02:27.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:02:27.617+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:02:27.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:02:27.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:02:27.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T01:02:57.960+0000] {processor.py:186} INFO - Started process (PID=2005) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:02:57.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:02:57.966+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:02:57.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:02:57.972+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:02:57.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:02:57.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:02:57.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.046 seconds
[2024-10-09T01:05:49.448+0000] {processor.py:186} INFO - Started process (PID=2080) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:05:49.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:05:49.453+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:05:49.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:05:49.457+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:05:49.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:05:49.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:05:49.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.044 seconds
[2024-10-09T01:06:20.612+0000] {processor.py:186} INFO - Started process (PID=2145) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:06:20.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:06:20.646+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:06:20.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:06:20.662+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:06:20.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:06:20.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:06:20.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.246 seconds
[2024-10-09T01:43:43.030+0000] {processor.py:186} INFO - Started process (PID=2203) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:43:43.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:43:43.035+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:43:43.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:43:43.041+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:43:43.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:43:43.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:43:43.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.066 seconds
[2024-10-09T01:44:13.242+0000] {processor.py:186} INFO - Started process (PID=2267) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:44:13.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:44:13.247+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:44:13.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:44:13.252+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:44:13.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:44:13.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:44:13.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.052 seconds
[2024-10-09T01:44:43.640+0000] {processor.py:186} INFO - Started process (PID=2331) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:44:43.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:44:43.645+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:44:43.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:44:43.650+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:44:43.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:44:43.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:44:43.678+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T01:45:13.901+0000] {processor.py:186} INFO - Started process (PID=2395) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:45:13.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:45:13.906+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:45:13.905+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:45:13.910+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:45:13.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:45:13.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:45:13.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.047 seconds
[2024-10-09T01:45:44.237+0000] {processor.py:186} INFO - Started process (PID=2455) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:45:44.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:45:44.243+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:45:44.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:45:44.248+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:45:44.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:45:44.249+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:45:44.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.052 seconds
[2024-10-09T01:46:14.817+0000] {processor.py:186} INFO - Started process (PID=2521) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:46:14.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:46:14.823+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:46:14.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:46:14.826+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:46:14.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:46:14.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:46:14.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T01:46:45.459+0000] {processor.py:186} INFO - Started process (PID=2583) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:46:45.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:46:45.463+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:46:45.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:46:45.466+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:46:45.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:46:45.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:46:45.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T01:47:16.162+0000] {processor.py:186} INFO - Started process (PID=2648) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:47:16.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:47:16.165+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:47:16.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:47:16.168+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:47:16.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:47:16.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:47:16.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T01:47:46.762+0000] {processor.py:186} INFO - Started process (PID=2713) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:47:46.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:47:46.765+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:47:46.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:47:46.769+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:47:46.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:47:46.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:47:46.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T01:48:17.465+0000] {processor.py:186} INFO - Started process (PID=2777) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:48:17.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:48:17.468+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:48:17.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:48:17.471+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:48:17.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:48:17.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:48:17.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T01:48:48.103+0000] {processor.py:186} INFO - Started process (PID=2841) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:48:48.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:48:48.107+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:48:48.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:48:48.111+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:48:48.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:48:48.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:48:48.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.036 seconds
[2024-10-09T01:49:18.786+0000] {processor.py:186} INFO - Started process (PID=2906) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:49:18.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:49:18.790+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:49:18.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:49:18.793+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:49:18.792+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:49:18.794+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:49:18.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.035 seconds
[2024-10-09T01:49:49.350+0000] {processor.py:186} INFO - Started process (PID=2971) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:49:49.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:49:49.355+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:49:49.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:49:49.358+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:49:49.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:49:49.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:49:49.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T01:50:19.924+0000] {processor.py:186} INFO - Started process (PID=3036) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:50:19.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:50:19.927+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:50:19.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:50:19.930+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:50:19.929+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:50:19.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:50:19.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.036 seconds
[2024-10-09T01:50:49.988+0000] {processor.py:186} INFO - Started process (PID=3100) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:50:49.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:50:49.993+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:50:49.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:50:49.996+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:50:49.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:50:49.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:50:50.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.035 seconds
[2024-10-09T01:51:20.317+0000] {processor.py:186} INFO - Started process (PID=3165) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:51:20.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:51:20.320+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:51:20.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:51:20.323+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:51:20.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:51:20.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:51:20.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T01:51:50.443+0000] {processor.py:186} INFO - Started process (PID=3230) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:51:50.444+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:51:50.447+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:51:50.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:51:50.450+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:51:50.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:51:50.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:51:50.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.033 seconds
[2024-10-09T01:52:21.280+0000] {processor.py:186} INFO - Started process (PID=3293) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:52:21.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:52:21.284+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:52:21.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:52:21.288+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:52:21.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:52:21.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:52:21.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T01:52:51.833+0000] {processor.py:186} INFO - Started process (PID=3356) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:52:51.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:52:51.839+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:52:51.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:52:51.844+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:52:51.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:52:51.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:52:51.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.040 seconds
[2024-10-09T01:53:22.032+0000] {processor.py:186} INFO - Started process (PID=3415) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:53:22.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:53:22.037+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:53:22.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:53:22.041+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:53:22.040+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:53:22.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:53:22.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.091 seconds
[2024-10-09T01:53:52.433+0000] {processor.py:186} INFO - Started process (PID=3480) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:53:52.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:53:52.438+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:53:52.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:53:52.441+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:53:52.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:53:52.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:53:52.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T01:54:22.689+0000] {processor.py:186} INFO - Started process (PID=3546) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:54:22.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:54:22.693+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:54:22.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:54:22.696+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:54:22.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:54:22.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:54:22.714+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T01:54:53.110+0000] {processor.py:186} INFO - Started process (PID=3610) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:54:53.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:54:53.116+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:54:53.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:54:53.126+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:54:53.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:54:53.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:54:53.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.047 seconds
[2024-10-09T01:55:23.413+0000] {processor.py:186} INFO - Started process (PID=3674) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:55:23.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:55:23.417+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:55:23.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:55:23.420+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:55:23.419+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:55:23.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:55:23.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T01:55:54.105+0000] {processor.py:186} INFO - Started process (PID=3737) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:55:54.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:55:54.110+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:55:54.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:55:54.113+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:55:54.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:55:54.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:55:54.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.035 seconds
[2024-10-09T01:56:24.378+0000] {processor.py:186} INFO - Started process (PID=3802) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:56:24.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:56:24.384+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:56:24.384+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:56:24.391+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:56:24.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:56:24.391+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:56:24.416+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T01:56:54.934+0000] {processor.py:186} INFO - Started process (PID=3867) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:56:54.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:56:54.939+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:56:54.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:56:54.943+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:56:54.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:56:54.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:56:54.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.038 seconds
[2024-10-09T01:57:25.630+0000] {processor.py:186} INFO - Started process (PID=3932) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:57:25.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:57:25.635+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:57:25.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:57:25.638+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:57:25.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:57:25.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:57:25.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.036 seconds
[2024-10-09T01:57:56.099+0000] {processor.py:186} INFO - Started process (PID=3997) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:57:56.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:57:56.102+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:57:56.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:57:56.105+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:57:56.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:57:56.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:57:56.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.033 seconds
[2024-10-09T01:58:26.492+0000] {processor.py:186} INFO - Started process (PID=4062) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:58:26.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:58:26.496+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:58:26.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:58:26.499+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:58:26.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:58:26.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:58:26.523+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.039 seconds
[2024-10-09T01:58:57.037+0000] {processor.py:186} INFO - Started process (PID=4126) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:58:57.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:58:57.041+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:58:57.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:58:57.045+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:58:57.043+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:58:57.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:58:57.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T01:59:27.963+0000] {processor.py:186} INFO - Started process (PID=4191) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:59:27.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:59:27.967+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:59:27.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:59:27.971+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:59:27.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:59:27.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:59:27.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.036 seconds
[2024-10-09T01:59:58.260+0000] {processor.py:186} INFO - Started process (PID=4256) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:59:58.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T01:59:58.264+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:59:58.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:59:58.268+0000] {logging_mixin.py:190} INFO - [2024-10-09T01:59:58.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T01:59:58.269+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T01:59:58.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.040 seconds
[2024-10-09T02:00:29.231+0000] {processor.py:186} INFO - Started process (PID=4320) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:00:29.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:00:29.235+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:00:29.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:00:29.238+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:00:29.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:00:29.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:00:29.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T02:00:59.539+0000] {processor.py:186} INFO - Started process (PID=4384) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:00:59.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:00:59.542+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:00:59.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:00:59.545+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:00:59.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:00:59.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:00:59.566+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.033 seconds
[2024-10-09T02:01:29.954+0000] {processor.py:186} INFO - Started process (PID=4449) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:01:29.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:01:29.958+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:01:29.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:01:29.962+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:01:29.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:01:29.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:01:29.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.040 seconds
[2024-10-09T02:02:00.231+0000] {processor.py:186} INFO - Started process (PID=4514) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:02:00.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:02:00.235+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:02:00.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:02:00.239+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:02:00.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:02:00.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:02:00.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.042 seconds
[2024-10-09T02:02:30.339+0000] {processor.py:186} INFO - Started process (PID=4579) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:02:30.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:02:30.344+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:02:30.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:02:30.356+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:02:30.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:02:30.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:02:30.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.052 seconds
[2024-10-09T02:03:00.622+0000] {processor.py:186} INFO - Started process (PID=4644) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:03:00.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:03:00.625+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:03:00.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:03:00.630+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:03:00.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:03:00.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:03:00.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.038 seconds
[2024-10-09T02:03:31.175+0000] {processor.py:186} INFO - Started process (PID=4709) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:03:31.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:03:31.179+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:03:31.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:03:31.183+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:03:31.181+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:03:31.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:03:31.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.039 seconds
[2024-10-09T02:04:02.072+0000] {processor.py:186} INFO - Started process (PID=4774) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:04:02.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:04:02.076+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:04:02.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:04:02.079+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:04:02.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:04:02.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:04:02.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T02:04:33.018+0000] {processor.py:186} INFO - Started process (PID=4838) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:04:33.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:04:33.022+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:04:33.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:04:33.025+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:04:33.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:04:33.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:04:33.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T02:05:03.999+0000] {processor.py:186} INFO - Started process (PID=4903) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:05:04.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:05:04.006+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:05:04.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:05:04.010+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:05:04.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:05:04.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:05:04.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.048 seconds
[2024-10-09T02:05:34.323+0000] {processor.py:186} INFO - Started process (PID=4968) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:05:34.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:05:34.326+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:05:34.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:05:34.329+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:05:34.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:05:34.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:05:34.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.033 seconds
[2024-10-09T02:06:04.800+0000] {processor.py:186} INFO - Started process (PID=5033) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:06:04.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:06:04.804+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:06:04.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:06:04.808+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:06:04.807+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:06:04.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:06:04.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.033 seconds
[2024-10-09T02:06:34.955+0000] {processor.py:186} INFO - Started process (PID=5098) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:06:34.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:06:34.958+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:06:34.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:06:34.962+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:06:34.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:06:34.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:06:34.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T02:07:05.258+0000] {processor.py:186} INFO - Started process (PID=5168) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:07:05.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:07:05.264+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:07:05.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:07:05.268+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:07:05.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:07:05.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:07:05.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.042 seconds
[2024-10-09T02:07:36.055+0000] {processor.py:186} INFO - Started process (PID=5232) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:07:36.056+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:07:36.059+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:07:36.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:07:36.063+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:07:36.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:07:36.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:07:36.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.036 seconds
[2024-10-09T02:08:06.712+0000] {processor.py:186} INFO - Started process (PID=5297) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:08:06.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:08:06.716+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:08:06.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:08:06.720+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:08:06.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:08:06.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:08:06.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.058 seconds
[2024-10-09T02:08:36.915+0000] {processor.py:186} INFO - Started process (PID=5362) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:08:36.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:08:36.918+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:08:36.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:08:36.921+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:08:36.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:08:36.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:08:36.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T02:09:07.213+0000] {processor.py:186} INFO - Started process (PID=5427) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:09:07.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:09:07.216+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:09:07.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:09:07.220+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:09:07.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:09:07.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:09:07.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.032 seconds
[2024-10-09T02:09:37.726+0000] {processor.py:186} INFO - Started process (PID=5491) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:09:37.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:09:37.729+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:09:37.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:09:37.734+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:09:37.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:09:37.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:09:37.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.034 seconds
[2024-10-09T02:10:08.320+0000] {processor.py:186} INFO - Started process (PID=5556) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:10:08.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:10:08.325+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:10:08.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:10:08.328+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:10:08.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:10:08.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:10:08.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.038 seconds
[2024-10-09T02:10:38.667+0000] {processor.py:186} INFO - Started process (PID=5621) to work on /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:10:38.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/mssql_test2.py for tasks to queue
[2024-10-09T02:10:38.671+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:10:38.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:10:38.675+0000] {logging_mixin.py:190} INFO - [2024-10-09T02:10:38.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/mssql_test2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/mssql_test2.py", line 18
    dag = DAG(
IndentationError: unexpected indent
[2024-10-09T02:10:38.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/mssql_test2.py
[2024-10-09T02:10:38.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/mssql_test2.py took 0.033 seconds
